site_name: Yoga Q/A Repository
site_description: Yogic Life Teachings & Answers

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest

nav:
  - Home: index.md
  - Philosophy: philosophy/
  - Creation Cycle: creation-cycle/
  - Mind: mind/
  - Mind-Body Connection: mind-body/
  - Food: food/README.md
  - Sadhana: sadhana/
  - Yogic Life: yogic-life/
  - Ethics: ethics/
  - Miscellaneous: misc/
